// <auto-generated />
using System;
using Deskflow.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskFlow.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005092058_DadosIniciais")]
    partial class DadosIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deskflow.Api.Models.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nomeCategoria");

                    b.HasKey("Id");

                    b.ToTable("Tb_categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Rede e Internet"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Software"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Acessos e Senhas"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Impressoras"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Telefonia"
                        });
                });

            modelBuilder.Entity("Deskflow.Api.Models.Entities.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SolicitanteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Solucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Chamados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            DataAbertura = new DateTime(2026, 9, 28, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "O notebook não liga mesmo conectado na tomada. O LED de carga não acende.",
                            Prioridade = "Alta",
                            SolicitanteNome = "Ana Souza",
                            Status = "EmAndamento",
                            Titulo = "Notebook não liga"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            DataAbertura = new DateTime(2026, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A conexão Wi-Fi cai várias vezes por hora na sala de reuniões do 2º andar.",
                            Prioridade = "Media",
                            SolicitanteNome = "Bruno Lima",
                            Status = "Aberto",
                            Titulo = "Wi-Fi caindo na sala de reuniões"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            DataAbertura = new DateTime(2026, 10, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Preciso do Office instalado no computador novo do setor financeiro.",
                            Prioridade = "Baixa",
                            SolicitanteNome = "Carla Mendes",
                            Status = "Aberto",
                            Titulo = "Instalação do pacote Office"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            DataAbertura = new DateTime(2026, 9, 25, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DataFechamento = new DateTime(2026, 9, 25, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Minha conta de e-mail foi bloqueada após várias tentativas de login.",
                            Prioridade = "Alta",
                            SolicitanteNome = "Diego Rocha",
                            Solucao = "Conta desbloqueada e senha redefinida. Usuário orientado a ativar o MFA.",
                            Status = "Fechado",
                            Titulo = "Senha do e-mail bloqueada"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            DataAbertura = new DateTime(2026, 10, 3, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "O monitor secundário apresenta listras verticais coloridas.",
                            Prioridade = "Media",
                            SolicitanteNome = "Eduarda Alves",
                            Status = "EmAndamento",
                            Titulo = "Monitor com listras na tela"
                        });
                });

            modelBuilder.Entity("Deskflow.Api.Models.Entities.Interacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.ToTable("Interacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Suporte - Marcos",
                            ChamadoId = 1,
                            DataRegistro = new DateTime(2026, 9, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Mensagem = "Testei com outro carregador e o problema persiste. Vou abrir o equipamento."
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Suporte - Marcos",
                            ChamadoId = 1,
                            DataRegistro = new DateTime(2026, 9, 28, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Mensagem = "Fonte interna com defeito. Peça solicitada, previsão de chegada em 2 dias."
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Suporte - Juliana",
                            ChamadoId = 3,
                            DataRegistro = new DateTime(2026, 10, 2, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Mensagem = "Licença disponível. Instalação agendada para amanhã às 9h."
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Suporte - Juliana",
                            ChamadoId = 4,
                            DataRegistro = new DateTime(2026, 9, 25, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            Mensagem = "Identidade do usuário confirmada por telefone. Iniciando desbloqueio."
                        });
                });

            modelBuilder.Entity("Deskflow.Api.Models.Entities.Chamado", b =>
                {
                    b.HasOne("Deskflow.Api.Models.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Deskflow.Api.Models.Entities.Interacao", b =>
                {
                    b.HasOne("Deskflow.Api.Models.Entities.Chamado", "Chamado")
                        .WithMany("Interacoes")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("Deskflow.Api.Models.Entities.Chamado", b =>
                {
                    b.Navigation("Interacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
