// <auto-generated />
using Deskflow.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskFlow.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005074155_CriacaoCategoria")]
    partial class CriacaoCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deskflow.Api.Models.Entities.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("codCategoria");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nomeCategoria");

                    b.HasKey("Id");

                    b.ToTable("Tb_categorias", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
